# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-10 10:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AreaConocimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=25)),
                ('estatus', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Canal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25)),
                ('descripcion', models.TextField()),
                ('fecha', models.DateTimeField()),
                ('logo', models.ImageField(upload_to='')),
                ('estatus', models.CharField(max_length=1)),
                ('areasConocimiento', models.ManyToManyField(to='redSocial.AreaConocimiento')),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('estatus', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=25)),
                ('descripcion', models.TextField()),
                ('fecha', models.DateTimeField()),
                ('logo', models.ImageField(upload_to='')),
                ('estatus', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Interes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=25)),
                ('estatus', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estatus', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Multimedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recurso', models.FileField(upload_to='')),
                ('tipo', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('estatus', models.CharField(max_length=1)),
                ('canal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='redSocial.Canal')),
                ('multimedia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='redSocial.Multimedia')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=25)),
                ('apellido', models.CharField(max_length=25)),
                ('fechaNacimiento', models.DateField()),
                ('sexo', models.CharField(max_length=1)),
                ('password', models.TextField(blank=True, null=True, verbose_name=django.db.models.deletion.SET_NULL)),
                ('foto', models.ImageField(upload_to='')),
                ('rol', models.CharField(max_length=1)),
                ('estatus', models.CharField(max_length=1)),
                ('areasConocimiento', models.ManyToManyField(to='redSocial.AreaConocimiento')),
                ('intereses', models.ManyToManyField(to='redSocial.Interes')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='redSocial.Usuario'),
        ),
        migrations.AddField(
            model_name='like',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='redSocial.Post'),
        ),
        migrations.AddField(
            model_name='like',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='redSocial.Usuario'),
        ),
        migrations.AddField(
            model_name='evento',
            name='propietario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='redSocial.Usuario'),
        ),
        migrations.AddField(
            model_name='comentario',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='redSocial.Post'),
        ),
        migrations.AddField(
            model_name='comentario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='redSocial.Usuario'),
        ),
        migrations.AddField(
            model_name='canal',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='redSocial.Usuario'),
        ),
    ]
