# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 03:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redSocial', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canal',
            name='nombre',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
