# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 03:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redSocial', '0002_auto_20170210_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multimedia',
            name='recurso',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='multimedia',
            name='tipo',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
